"""Add role field to user

Revision ID: 77efc1e55189
Revises: d4cf9af6587d
Create Date: 2023-05-24 09:48:28.493781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77efc1e55189'
down_revision = 'd4cf9af6587d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
