"""change many to many logic

Revision ID: cd36ba449ce2
Revises: f9dcbace1397
Create Date: 2023-05-03 15:22:32.355339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd36ba449ce2'
down_revision = 'f9dcbace1397'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
