"""change delete logic in all tables

Revision ID: d4cf9af6587d
Revises: cd36ba449ce2
Create Date: 2023-05-03 15:55:55.946694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cf9af6587d'
down_revision = 'cd36ba449ce2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cost', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cost', 'responsible_person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('FK__cost__bank_accou__1EA48E88', 'cost', type_='foreignkey')
    op.drop_constraint('FK__cost__responsibl__1F98B2C1', 'cost', type_='foreignkey')
    op.create_foreign_key(None, 'cost', 'bank_account', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cost', 'personal', ['responsible_person_id'], ['id'], ondelete='SET NULL')
    op.alter_column('income', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('FK__income__bank_acc__18EBB532', 'income', type_='foreignkey')
    op.create_foreign_key(None, 'income', 'bank_account', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('FK__income_pr__produ__236943A5', 'income_product', type_='foreignkey')
    op.drop_constraint('FK__income_pr__incom__22751F6C', 'income_product', type_='foreignkey')
    op.create_foreign_key(None, 'income_product', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'income_product', 'income', ['income_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income_product', type_='foreignkey')
    op.drop_constraint(None, 'income_product', type_='foreignkey')
    op.create_foreign_key('FK__income_pr__incom__22751F6C', 'income_product', 'income', ['income_id'], ['id'])
    op.create_foreign_key('FK__income_pr__produ__236943A5', 'income_product', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.create_foreign_key('FK__income__bank_acc__18EBB532', 'income', 'bank_account', ['bank_account_id'], ['id'])
    op.alter_column('income', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'cost', type_='foreignkey')
    op.drop_constraint(None, 'cost', type_='foreignkey')
    op.create_foreign_key('FK__cost__responsibl__1F98B2C1', 'cost', 'personal', ['responsible_person_id'], ['id'])
    op.create_foreign_key('FK__cost__bank_accou__1EA48E88', 'cost', 'bank_account', ['bank_account_id'], ['id'])
    op.alter_column('cost', 'responsible_person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cost', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
