"""create change connections

Revision ID: f9dcbace1397
Revises: fcac950c58e2
Create Date: 2023-04-28 16:01:14.598801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9dcbace1397'
down_revision = 'fcac950c58e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
